return {
    'm4xshen/hardtime.nvim',
    lazy = false,
    dependencies = { 'MunifTanjim/nui.nvim' },
    opts = {
        max_time = 5000,
        max_count = 2,
        timeout = false,
        resetting_keys = {},
        restricted_keys = {
            ['w'] = { 'n', 'x' },
            ['W'] = { 'n', 'x' },
            ['e'] = { 'n', 'x' },
            ['E'] = { 'n', 'x' },
            ['b'] = { 'n', 'x' },
            ['B'] = { 'n', 'x' },
            ['J'] = { 'n', 'x' },
            ['c'] = { 'n' },
            ['C'] = { 'n' },
            ['d'] = { 'n' },
            ['x'] = { 'n' },
            ['X'] = { 'n' },
            ['y'] = { 'n' },
            ['Y'] = { 'n' },
            ['p'] = { 'n' },
            ['P'] = { 'n' },
            ['gp'] = { 'n' },
            ['gP'] = { 'n' },
            ['<'] = { 'n' },
            ['>'] = { 'n' },
        },
        disabled_keys = {
            ['<C-w>c'] = { 'n' },
            ['<ESC>'] = { 'n' },
        },
    },
}
